server:
  port: 18082
  servlet:
    context-path: /wechat
spring:
  application:
    name: wechat
eureka:
  client:
    service-url:
      defaultZone: http://wwivan:123456@localhost:7001/eureka/
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true